version: '2'
services:
  ws:
    environment:
      - JAVA_OPTS=-Derror.whitelabel.enabled=true -Dendpoints.enabled=true -Dendpoints.sensitive=false
    #  - JAVA_OPTS=-Dspring.profiles.active=dev
    volumes:
      - ./statics:/usr/local/tomcat/data

  front:
    environment:
      - VBOARD_API_ENDPOINT=http://localhost:8080
    volumes:
      - ./statics:/var/vboard/statics
      # Mouting the following directory "overrides" the one in the built container.
      # We do this to benefit from "grunt watch" regenerating the statics
      #!! Does not work atm because grunt delete/recreate this directory
      - ./vboard-front/grunt-target:/var/www/vboard
